### PR TITLE
Re-enable deterministic site builds

### PR DESCRIPTION
**Pull request by achow101**
This PR makes the site builds deterministic again. The two sources of non-determinism were the cache busting technique, and the `pubDate` and `lastBuildDate` from the blog's RSS feed.

To address the first source of non-determinism, the cache busting technique was simply removed. This technique involved appending the build timestamp to every image and css file loaded. Since the site is largely static and images and css are unlikely to be constantly changing, I do not think it is necessary to keep this technique around. Removing it also makes the site build deterministically.

To address second source of non-determinism, the `pubDate` and `lastBuildDate` fields of the blog's RSS feed have been changed from the actual build date to the date of the most recent blog post. This makes the builds deterministic while also ensuring the the RSS feed will be updated when new blog posts are made.

This addresses the second point of #14.

### CODE REVIEW

**Comment by harding** [comment]
utACK.  Thanks!

**Comment by kek-coin** [comment]
Just to confirm it is running deterministically, these are the results on my machine:
```bash
$ sha256sum _site/sha256sums.txt
4f2edea1c87949456eb9b072d80ef2625a0984ad782cdbd6b2a125654c73d61d  _site/sha256sums.txt
```

**Comment by harding** [comment]
@kek-coin #17 needs to be merged before there's any hope of determinism, and the best way to check will be by running: `make manual-check-diff-sha256sums` after building the `master` branch as that Make target will tell you what files differ between your local build and the deployed site (assuming no one is serving you specially).

**Comment by harding** [comment]
I get a different hash (Debian 9):

```text
user@devbco:~/btcinformation.org$ git log --oneline -1
752e64b2 Use the date of the most recent post for blog rss
user@devbco:~/btcinformation.org$ sha256sum _site/sha256sums.txt 
3a1e21b370454bb63f1c02ddfa77ed9fb757f0475c6d8a387b2d7237ada5f75c  _site/sha256sums.txt
```

Here's my sha256sums.txt if you want to diff: https://0bin.net/paste/F7VT6yjI9mg8pmNA#stvzkWuYVSSKMUbK7Je5vSwAyQEJiytSYJlmyRJxgeH

**Comment by kek-coin** [comment]
Diff:
```bash
$ diff sha256sums.txt sha256sums_harding.txt
189c189
< 2ed6999e4e24c3466eecdf0b06f1e72a9fa6a0db6799e6f3753d559fe6d1e99d  _site/en/rss/blog.xml
---
> a2f85399b3a62abcbbb9f2b88226b9633cc846d426ce82beaed84c9acad3234b  _site/en/rss/blog.xml
976c976
< 62a9fb9e2320b9d82d31008508fd0c16796a1eda92ea80df8b1dc8aaa52024d5  _site/robots.txt
---
> 844490a4b1ed467d1524f3422a3c057819e860a165c85039bc941189326a367f  _site/robots.txt
981c981
< 52d50e683d9c47e3286a49b275b092d16269375fdbe7df9e1888628332e82b2f  _site/sitemap.xml
---
> 484c1e64ec9f1ebb4b44c5041696be777623731c24057f704630f8afeceae534  _site/sitemap.xml
```

**Comment by kek-coin** [comment]
@harding did you run it on the `determinism` branch? My git log is:
```bash
$ git log --oneline
752e64b2 (HEAD -> determinism, origin/determinism) Use the date of the most recent post for blog rss
```

**Comment by harding** [comment]
I know what's causing the robots.txt difference (an env variable I forgot to turn off).  The blog and sitemap difference is probably because the times are localilized (I'm in UTC-04:00).

Yeah, we're on the same commit (the branch name doesn't matter).

**Comment by kek-coin** [comment]
Times should probably not be localized? And yeah, noticed the commit hash was identical so removed my comment :)

**Comment by harding** [comment]
Maybe try quickly patching your `_config.yml` like this:

```diff
--- a/_config.yml
+++ b/_config.yml
@@ -1,3 +1,5 @@
+timezone: UTC
+
 langsorder:
 - 'id'
 - 'da'
```

With that, I get the hash: `12d5d67f8510f9c21483f07097ff0641aea9431e6a3b2a612c0c00575c59a9bd  _site/sha256sums.txt`

If that works, @achow101 can just add that to this branch.

**Comment by kek-coin** [comment]
Unfortunately, that does not seem to do the trick;
```036dd4886cf7b4353c5612882def74fa2aec9807e96344cdcc582d93b50c033a  _site/sha256sums.txt```.

[Full sha256sums.txt](https://0bin.net/paste/9sFAqN28BAX2jLn4#2igdkIsa94wAy6pCEaomxEIonzasceZ7j4u6bpdPJim).

**Comment by harding** [comment]
```
user@devbco:~/btcinformation.org$ diff ~/foo _site/sha256sums.txt 
981c981
< 52d50e683d9c47e3286a49b275b092d16269375fdbe7df9e1888628332e82b2f  _site/sitemap.xml
---
> 484c1e64ec9f1ebb4b44c5041696be777623731c24057f704630f8afeceae534  _site/sitemap.xml
```

My sitemap: https://0bin.net/paste/VirgsLLL3IXkm2T1#sZU+DihfmJ0a23+UmfxcqWZzi9dZlhS5Koh9dyNqMvI

**Comment by kek-coin** [comment]
[Mine](https://0bin.net/paste/Z-96T9pY61c-bUlr#gm88cfYRMDeQl78l-ZSxOz6M2wHQOyO79rXfu22DJYh).

**Comment by harding** [comment]
Looks like the file ordering is non-deterministic (probably based on Unix file ctime or mtime) from the _plugins/sitemap.rb plugin.  It's probably easy enough to stick a sort in there somewhere, but my ruby is a bit rusty and I'm out of time for today.

A really simple solution is just removing the sitemap file and the plugin.  Search engines will eventually crawl all of our pages even without one.  (And the sitemap appears to be broken anyway: I think we have a lot more pages than it lists.)

**Comment by achow101** [comment]
My sha256sums.txt file is `a4f80d8ca03e78cba058793572fd5edb4c7b4612cae74063b40858e70b89cabe  sha256sums.txt`.

I'll look at the timezone and sitemap stuff.

**Comment by achow101** [comment]
I have pushed a few more commits. The first one sets the timezone to UTC as @harding suggested above. The second commit sorts the entries before going into the sitemap.

sha256 of sha256sums: `95db3e3880b8ae5750f4efa40732f4b84b9c0e776750eff20cd8ab4d8764f59c`
[sha256sums.txt file itself](https://0bin.net/paste/fov0rfwqDc1oMCt5#dPM3JMVQtjMySWa+evavbmyACmsDJO3qLArj2PfxMmt)
[sitemap.xml file](https://0bin.net/paste/rDFItRxizu2KfaP3#j44LOT939y3s1nGBPVeH-r/K5E6vrNPA1ugcZzHHoXA)

When testing the new commits, keep in mind that you will probably have to `make clean` first.

**Comment by kek-coin** [comment]
Identical sha256 of sha256sums.txt here :+1:

**Comment by kek-coin** [comment]
Perhaps @emmonspired could also test this on OSX?

**Comment by harding** [comment]
Same hash as @achow101 in https://github.com/achow101/btcinformation.org/pull/17#issuecomment-411151808 here.  :tada:

**Review by harding — APPROVED** [review]
ACK 1558b3a7acb6f5df9848db702a704c3062d6ee76

Tested translation plugin changes by building site with and without this commit and verifying all files (except the expected changed sitemap) were identical between the two builds.

**Comment by emmonspired** [comment]
I had to do some mac osx tricks to install sha256sum @kek-coin 

```brew reinstall coreutils
sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum
sudo ln -s /usr/local/bin/gsha512sum /usr/local/bin/sha512sum
```

Reproduction steps:
git checkout determinism && git pull && bundle install && make clean && make

> sha256sum _site/sha256sums.txt
```e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  _site/sha256sums.txt```

**Comment by kek-coin** [comment]
Can you 0bin the sha256sums.txt? Just to confirm you're using the correct commit, what's the output of `git log --oneline -1`?

**Comment by emmonspired** [comment]
$ git log --oneline -1
1558b3a7 (HEAD -> determinism, origin/determinism) Sort URLs before adding to the sitemap

**Comment by emmonspired** [comment]
Actually it just occurred to me that when i was getting my dev environment setup before (Mac OSX) I only fully tested `make preview` which worked. but this make all dies:

Lang nl disabled
                    done in 75.269 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
xargs: illegal option -- d
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
make: *** [build] Error 1

**Comment by emmonspired** [comment]
Looks like there is more to fix on the mac side, and i'm not sure where. Make Preview works fine, but make does with the above error.

**Comment by achow101** [comment]
Instead of `make`, do `make deployment`

**Comment by emmonspired** [comment]
By the way, I just found a fix for the Mac OSX environment for the -d command missing for the xargs required for the build. I'm going to add these to PR #18 based on https://superuser.com/questions/467176/replacement-for-xargs-d-in-osx

brew install findutils
PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"

This is now my output:

```
Lang nl disabled
                    done in 94.436 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by kek-coin** [comment]
@achow101 should that matter? For me the outcome is identical.

**Comment by emmonspired** [comment]
Yes it mattered @kek-coin - before the build was failing and nothing was in the sha file.

Got further, did `make deployment` after the above changes.

$ sha256sum _site/sha256sums.txt 
08990cc725fbbd617934050c6916bbe766afacd20bd632746aa62f22f2625c7c  _site/sha256sums.txt

**Comment by emmonspired** [comment]
As per @kek-coin request to put the full contents on 0bin https://0bin.net/paste/4e4m+RaDNWza3eb8#hUdxs1WWJx31OS1DWgILcBed5M8wPg65bY9H4r24Iw1

**Comment by kek-coin** [comment]
From comparing `sha256sums.txt` @emmonspired gave me, there were only 2 differences:

* All his filepaths were prefixed with `_site//` while mine were prefixed with `_site/`.
* The order of filenames in the `sha256sums.txt` was different.

After replacing all instances of `//` with `/` and sorting all entries alphabetically by hash (in both files), the files were identical.

**Comment by achow101** [comment]
Any ideas what might be causing the difference in @emmonspired's the sha256sums.txt file? As long as the hashes of all of the other files in the build are identical, then I think this is fine to merge as is. But it would be nice to also make the sha256sums.txt file deterministic too.

**Comment by kek-coin** [comment]
https://github.com/achow101/btcinformation.org/blob/determinism/Makefile#L108 seems to be the place where it is generated.... I have no idea why it ends up with nondeterministic sorting - the filenames are `sort`ed before passing them to `sha256sum`.

**Comment by harding** [comment]
@kek-coin oh, I didn't realize we had a bare `sort` command in there.  Look at https://github.com/achow101/btcinformation.org/blob/master/Makefile#L235 to see how to make sort deterministic across locales.

**Comment by kek-coin** [comment]
We (@emmonspired and I) both had to do `export LC_ALL="en_US.UTF-8" && export LANG="en_US.UTF-8"` for this branch to build, though, so that shouldn't make a difference?

**Comment by harding** [comment]
@kek-coin then maybe not.  Could be that his Darwin/BSD `sort` is different from the GNU `sort` when it comes to string order in the same locale.

**Comment by achow101** [comment]
I rebased onto master to get the LC_ALL changes in. I've also added a commit that should at least fix the `_site//` problem. Hopefully it also makes sort actually sort correctly.

```
$ sha256sum _site/sha256sums.txt 
bc67915221f349b5b21866208b9a44f0165ab9cae1999a9e804365fdeade89d9  _site/sha256sums.txt
```
[sha256sums.txt](https://0bin.net/paste/OwGyCc+5uzLiKp1f#Fter9j5bAuX-9NLtQ0LLEsqQQipcXQBK1nHn2cnl0SW)

**Comment by emmonspired** [comment]
I plan to check this out later tonight.

**Comment by kek-coin** [comment]
Identical `sha256sum _site/sha256sums.txt` output for me.

**Comment by emmonspired** [comment]
Finally got around to this. I have a different sha256sum.

sha256sum _site/sha256sums.txt 
dafd23c4f162afa698f4e71be20c0878e866f21a20269e22fc74472ee0f49400  _site/sha256sums.txt

Here are the contents of the _site/sha256sums.txt file: https://0bin.net/paste/DINFQfIxnneuGZPN#Qg6ZFys8Qq3X3Z3zfY4gv9cTWKeiGAitEctTHKtKesM

**Comment by kek-coin** [comment]
Difference seems to be that @emmonspired's filenames are sorted case-sensitive (uppercase `C` before lowercase `a`), while on linux they are not.

**Comment by kek-coin** [comment]
Using GNU sort from `brew install coreutils` **might** fix the problem, but I'm reading that locales on OSX might be broken. Hopefully that does not apply to `en_US.UTF-8`.

**Comment by emmonspired** [comment]
I already have coreutils which come part of the xcode dependencies. Other people report sort differences between mac and other platforms as well, although there doesn't seem to be a solution given: https://stackoverflow.com/questions/27395317/why-does-utf-8-text-sort-in-different-order-between-os-x-and-linux

**Comment by achow101** [comment]
@emmonspired Can you try the latest commit? I set `sort` to ignore case.

```
$ sha256sum _site/sha256sums.txt 
bc67915221f349b5b21866208b9a44f0165ab9cae1999a9e804365fdeade89d9  _site/sha256sums.txt
```

**Comment by emmonspired** [comment]
Different again. sha256sum _site/sha256sums.txt 
3ea8807cfe5212a5b5c8e757ebece1d456d46d1f5ad0699e420d01ac7a2ab822  _site/sha256sums.txt

Here's the file: https://0bin.net/paste/cXYOeua9ghhj7FnZ#xnVrzrwWVDpdm+WryY53RV2fbRCmw0A6PHtecQVGJDY

**Comment by achow101** [comment]
It seems like the problem is now with the ordering of `.` and `-`.

Since the problem now is just sort order differences between Mac OSX and Linux, I'm just going to merge this now. `make manual-checks` will check the sha256sums.txt file but will ignore the sort order differences, so this is fine as long as the hashes within the sha256sums.txt files match, which they do.

**Pull request merged**
