### PR TITLE
rebrand GreenBits and GreenAddress iOS as Blockstream Green

### PR DESCRIPTION
**Pull request by greenaddress**
Replaces GreenBits (for Android) and GreenAddress for iOS with Blockstream Green for both

### CODE REVIEW

**Comment by harding** [comment]
The corresponding PR for Bitcoin.org is https://github.com/bitcoin-dot-org/bitcoin.org/pull/2901

As always, I'm eager to hear what @crwatkins discovers in his review.  Regarding the discussion on the above PR about whether or not this is an update of an existing wallet or a new wallet subject to the three-month wait period, I'd suggest considering a compromise position.  Because GA has an existing userbase, I'd expect their migrating users to find issues faster than normal for a new wallet with no userbase, so perhaps an abbreviated wait period is warranted for that reason plus this not being an entirely new codebase (provided the usual "no concerning feedback").

**Comment by greenaddress** [comment]
3 months have passed since the original submission, unfortunately i don't think anyone had a chance to review it yet, in any case let me know if you have feedback or if you would like me to rebase the PR

thanks!

**Comment by crwatkins** [comment]
My [review is here](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2901#issuecomment-507094990).

**Comment by greenaddress** [comment]
@harding 

The PR on GitHub was closed citing issues with unrelated desktop app and delays in getting replies as well as the 2of2 model (we do have a recovery tool for it at https://GitHub.com/GreenAddress/garecovery). Do you want to close this one too or go ahead? @crwatkins spent some time reviewing and provided a recommendation for inclusion months ago before (1 week ago) the PR was closed swiftly.

For what is worth the response time on GitHub isn't always prompt from me however our user support is swifter than ever (mostly over email, telegram, twitter)

**Comment by harding** [comment]
I'd be interested in hearing @crwatkins's opinion here.

For my own curiosity, may I inquire about whether your previously-announced plan to switch to using `OP_CSV` is near-future or far-future?  Also, how will the user wallet know the public key for the Blockstream side?  (E.g., will it be (1) a fixed pubkey used for all BS Green transactions, (2) a per-transaction pubkey generated by the BS server and provided to the wallet, or (3) a per-transaction pubkey generated by the wallet using a per-user HD public derivation path.  I ask because options 1 and 3 are easy to create static backups for, but option 2 would still require users backup after every transaction like the current nlocktimes.zip mechanism.)

**Comment by greenaddress** [comment]
> For my own curiosity, may I inquire about whether your previously-announced plan to switch to using OP_CSV is near-future or far-future? 

Liquid is already using OP_CSV and the only thing that blocked migration of testnet and mainnet was the desktop app having support. The desktop app is close to ready, some polishing required, packaging for windows/mac/linux (is written in Qt) and hardware wallet integration missing. I think we will release the desktop app before the end of the year and subsequently turn on CSV.

> Also, how will the user wallet know the public key for the Blockstream side?

The xpub is public and hardcoded in the open source mobile apps and in the recovery tool https://github.com/Blockstream/gdk/blob/49a1bf79759658ef96bbf71799982f6dff27bdbc/src/network_parameters.cpp#L127 and https://github.com/greenaddress/garecovery/blob/master/gaservices/utils/gaconstants.py#L40  respectively

So option (3) and all it requires is the generic xpub from the server, your mnemonic and a full node for full recovery (and either our recovery tool to facilitate it or a user written script) - in the future we plan to make a GUI recovery tool - either integrated in the wallets or standalone.

**Comment by harding** [comment]
That CSV scheme allowing static backup (mnemonic + recovery tool) seems sound to me at a design level, and I wouldn't describe a wallet using that scheme as custodial, so I think that bodes well for getting your re-listed on Bitcoin.org.

For this listing, I wait to see if Craig has any public comments since his review for Bitcoin.org a couple months ago.

**Comment by crwatkins** [comment]
The OP_CSV change will be very welcome.  The older GreenAddress wallet used nag banners on the main page to encourage enabling 2FA which was required for backups.  Blockstream Green doesn't have any such banners nor does it even mention the backups on the settings page until after email 2FA is enabled.  I suspect a majority of new users will have no backup for the Green servers going away.  OP_CSV would change that.

I'm still concerned about support issues.  I checked the Blockstream Green support page and followed the instructions which suggested sending an email to info@greenaddress.it.  I have not yet received a reply to my email from almost two weeks ago on 24 August.

**Comment by alessandro-saglimbeni** [comment]
@crwatkins We are sorry for the delayed response, unfortunately august was a month of vacations for some in the staff, and priority was given to support requests coming from users in trouble.

FYI there are several channels – besides from the projects' repos – where people can ask for support, clarifications, or new feature. They are all listed on our documentation https://docs.blockstream.com/green/support.html

**Comment by achow101** [comment]
This project is no longer being maintained.

**Pull request closed without merging**
