### PR TITLE
Makefile: use LC_ALL rather than LANG to overide all localization settings

### PR DESCRIPTION
**Pull request by harding**
This should address the discussion here: https://github.com/achow101/btcinformation.org/pull/18#discussion_r208224438

On Unix, the `LC_ALL` variable overrides all other localization variables, so setting this to a uniform value in the Makefile should ensure all builders get consistent results without them needing to override their own localization settings.

Although this branch is based on master, I tested it on the deterministic build branch and found no differences in content (except commit.txt that lists the latest commit) between:

- Building on commit before this one, the deterministic commit
- Building with this commit and normal locale (en_US.UTF-8)
- Building with this commit and my locale set to the ASCII (not-UTF-8) C locale

CC: @kek-coin and @emmonspired from original discussion

### CODE REVIEW

**Comment by emmonspired** [comment]
Checking it out.

**Review by emmonspired — CHANGES_REQUESTED** [review]
Still getting the same error, unfortunately. Environment: Mac OSX

**Comment by emmonspired** [comment]
Still need to run this before make in order to get a successful build:

export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

**Comment by harding** [comment]
Are you getting the same error as before?  Can you confirm you have the upgraded Makefile, e.g. this should print several lines:

    grep LC_ALL Makefile

**Comment by emmonspired** [comment]
Same error as before, yes. Steps to reproduce on Mac OSX:

curl -L https://patch-diff.githubusercontent.com/raw/achow101/btcinformation.org/pull/19.patch > Makefile.patch

git apply --check Makefile.patch 

git apply Makefile.patch 

git diff Makefile

```
demmonss-MacBook-Pro:btcinformation.org demmons$ git diff Makefile
diff --git a/Makefile b/Makefile
index eb163bab..d890ab34 100644
--- a/Makefile
+++ b/Makefile
@@ -16,7 +16,7 @@ default: clean build
 
 ## `make preview`: start the built-in Jekyll preview
 preview: clean
-       $S export LANG=C.UTF-8 ; export ENABLED_LANGS="en" ; bundle exec jekyll serve --incremental
+       $S export LC_ALL=C.UTF-8 ; export ENABLED_LANGS="en" ; bundle exec jekyll serve --incremental
 
 ## `make test`: don't build, but do run all tests
 test: pre-build-tests post-build-tests
@@ -99,12 +99,12 @@ manual-checks: manual-check-diff-sha256sums
 ERROR_ON_OUTPUT="sed '1s/^/ERROR:\n/' | if grep . ; then sed 1iERROR ; false ; else true ; fi"
 
 clean:
-       $S bundle exec jekyll clean
+       $S export LC_ALL=C.UTF-8 bundle exec jekyll clean
 
 ## Always build using the default locale so log messages can be grepped.
 ## This should not affect webpage output.
 build:
-       $S export LANG=C.UTF-8 ; export ENABLED_LANGS="en" ; bundle exec jekyll build 2>&1 | tee $(JEKYLL_LOG)
+       $S export LC_ALL=C.UTF-8 ; export ENABLED_LANGS="en" ; bundle exec jekyll build 2>&1 | tee $(JEKYLL_LOG)
        $S grep -r -L 'Note: this file is built non-deterministically' _site/ \
          | egrep -v 'sha256sums.txt' \
```

make preview

```
Lang nl disabled
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    Invalid US-ASCII character "\xE2" on line 1917
jekyll 3.0.1 | Error:  Invalid US-ASCII character "\xE2" on line 1917
make: *** [preview] Error 1
```

The problem goes away if I execute those export commands above.

**Comment by harding** [comment]
Weird.  Sorry I need to keep bothering you with questions; obviously I don't have a MacOS machine to test on myself.  Can you try with just `export LANG="en_US.UTF-8"` ?

If that works, can you try with:

    export LANG="C.UTF-8"

Or if the first export didn't work, can you try with:

    export LC_ALL="C.UTF-8"
    export LANG="C.UTF-8"

**Comment by emmonspired** [comment]
Sorry to be the bearer of bad news, but those suggestions didn't work.

```
  524  clear
  525  export LANG="en_US.UTF-8"
  526  make preview
  527  export LANG_ALL="C.UTF-8"
  528  make preview
  529  export LANG="C.UTF-8"
  530  make preview
  531  history
```

**Comment by emmonspired** [comment]
After using this patch, even my suggested exports don't work. I had to revert the patch and then issue them again: 



git reset --HARD head

export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

**Comment by emmonspired** [comment]
Yeah, only builds after removing this patch now.

**Comment by harding** [comment]
Ok, well that's sort of good news that the problem seems to be just the C.UTF-8 locale, and a web search supports that MacOS actually doesn't support this at the moment.  I updated the PR to use en_US.UTF-8 as the default so that everyone on all platforms still uses the same locale.  This is more likely to break on Linux systems used by non-English speakers, but most devs I think have the en_US locale installed anyway, so hopefully it's not too bad.

If you could test the PR again, I'd appreciate that.  This could also use testing by other contributors to the site to ensure it doesn't break their setup.

**Comment by emmonspired** [comment]
@harding confirmed, works with en_US.UTF-8

```
Lang nl disabled
                    done in 61.1 seconds.
 Auto-regeneration: enabled for '.'
Configuration file: /Users/demmons/sandbox/btcinformation.org/_config.yml
    Server address: http://127.0.0.1:4000//
  Server running... press ctrl-c to stop.
```

**Review by emmonspired — APPROVED** [review]
Confirmed: works with LC_ALL=en_US.UTF-8

**Comment by kek-coin** [comment]
tACK

**Comment by achow101** [comment]
utACK e692ec74fa03b59e810e7d0eaff28912a555c242

**Pull request merged**
