### PR TITLE
Wasabi wallet

### PR DESCRIPTION
**Pull request by lontivero**
This PR is for requesting the inclusion of Wasabi wallet.
 
Wasabi Wallet is an open-source, cross-platform, non-custodial, privacy focused Bitcoin wallet for Desktop. Its main features are built-in Tor, CoinJoin and coin control.

# Screenshot
image

# References

* Tor website: http://wasabiukrxmkdgve5kynjztuovbg43uxcbcxn6y2okcrsg7gb6jdmbad.onion
* Clearnet website: https://wasabiwallet.io/
* GitHub (Source Code): https://github.com/zkSNACKs/WalletWasabi
* Technical Overview and Future Plans: https://github.com/zkSNACKs/Meta

----

# Basic requirements

https://github.com/achow101/btcinformation.org/blob/master/docs/managing-wallets.md

### 1. Feedback

> Sufficient users and/or developers feedback can be found without concerning issues, or independent security audit(s) is available

#### Users

Me and some other developers address user feedbacks/questions/issues/etc.. on /r/WasabiWallet. We also have Telegram group and other content created by our users. We recently started to collect them in a place we call the Dojo.

#### Developers

Comparing to all other desktop wallets on the site, our GitHub page seems to be in a better shape/more active if we look a the issues, pull requests, number of contributors, stars, number of commits, etc.. than arcbit's, bither's greenaddress's and msigna's and it may be somewhat even to Armory's.

### 2. Issues

>No indication that users have been harmed considerably by any issue in relation to the wallet
No indication that security issues have been concealed, ignored, or not addressed correctly in order to prevent new or similar issues from happening in the future
No indication that the wallet uses unstable or unsecure libraries
No indication that changes to the code are not properly tested
No concerning bug is found when testing the wallet

No.

### 3. Maturity

> Wallet was publicly announced and released since at least 3 months

By 31 January 2019 (Wasabi Wallet has only been released in August 1, 2018)

### 4. Website

> Website supports HTTPS and 301 redirects HTTP requests

Yes: http://wasabiwallet.io

(Well, except the onion mirror, but onions doesn't use/need HTTPS anyway: http://wasabiukrxmkdgve5kynjztuovbg43uxcbcxn6y2okcrsg7gb6jdmbad.onion)

> SSL certificate passes Qualys SSL Labs SSL test

https://www.ssllabs.com/ssltest/analyze.html?d=wasabiwallet.io

image
image

> Website serving executable code or requiring authentication uses HSTS with a max-age of at least 180 days

Yes.
image

### 5. Company

> The identity of CEOs and/or developers is public

Yes: https://zksnacks.com/#contact

### 6. Best Practices

> Avoid address reuse by displaying a new receiving address for each transaction in the wallet UI

Yes, when money arrives to an address it even disappears from the list.

> Avoid address reuse by using a new change address for each transaction

Yes.

> Uses deterministic ECDSA nonces (RFC 6979)

Yes. NBitcoin uses deterministic nonces by default. https://github.com/Metacosa/nbitcoin/blob/master/NBitcoin/Crypto/ECKey.cs#L71

> User has access to private keys

Yes.

> If private keys or encryption keys are stored online: ...
If user has exclusive access over its private keys: ...
If user has no access to some of the private keys in a multi-signature wallet: ...
If hardware wallet: ...

No.

### 7. Optional Criterias

> Received independent security audit(s)

No.

> Does not show "received from" Bitcoin addresses in the UI

It doesn't.

> Provides a bug reporting policy on the website

From the website:

image
image

From the software:

image

> Website serving executable code or requiring authentication is included in the HSTS preload list

Website response with HSTS header.

>Supports HD wallets (BIP32)

Yes.

>Provides users with step to print or write their wallet seed on setup

Yes.

>Uses a strong KDF and key stretching for wallet storage and backups

Wallet storage is protected by the algorithm described in bip38 which uses scrypt as KDF.

> Encrypt the wallet by default

Yes.

----

# Feedback

If you have any feedback as to what should be improved on the wallet in order to make it to the site we are all ears of.

### CODE REVIEW

**Comment by harding** [comment]
Thanks for the PR!

I suggest waiting for @crwatkins's evaluation of the equivalent PR to Bitcoin.org (https://github.com/bitcoin-dot-org/bitcoin.org/pull/2788).  I previously emailed him a few comments about various aspects of Wasabi and I know he'll perform a detailed evaluation that may catch issues (or find features) I'm unaware of.

**Comment by lontivero** [comment]
I've changed the transparency check. Is it the rest okay?

**Comment by ghost** [comment]
Since the PR to Bitcoin.org is [merged](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2788), can this PR be merged also?

**Comment by achow101** [comment]
This project is no longer being maintained.

**Pull request closed without merging**
